### ISSUE TITLE
when the app is disabled and enabled again, the users should not be forced to accep the tos again

### ISSUE THREAD

**Issue by GretaD** [nextcloud/terms_of_service#1000]
When i disable the ToS app and enable it again, all users need to agree to the ToS again. Imho this shouldn't be the case as the status of accepted ToS is stored in the DB.

**Comment by nickvergessen** [comment]
Can not reproduce. The signing status is saved in oc_preferences and disabling an app does not remove them.

**Comment by nickvergessen** [comment]
This happens only on mobile phones. The push notification is sent, even when the user had accepted already:
https://github.com/nextcloud/terms_of_service/blob/ad30fba4a5b846661dc9f46b77591895cd7fe2de/lib/Notifications/Notifier.php#L66-L72

We should make sure to not push the notification for users that accepted the ToS already for any country/language.

**Comment by nickvergessen** [comment]
When reseting for everyone we are also "live" looping over all users (instead of a background job) that could take quite long.
