### ISSUE TITLE
Terms of Service does not show up for shared folders through email.

### ISSUE THREAD

**Issue by perphilip** [nextcloud/terms_of_service#119]
Hi,
We are setting up a service for users to upload and download files and would like for the ones that get share links in their email to also have to approve Terms of Service before uploading or downloading anything to and from the server. Is that possible to implement or have I missed it in the settings somewhere?

Thanks!

**Comment by brtptrs** [comment]
It would be great if this could be a configuration option.

**Comment by nickvergessen** [comment]
What exactly?

**Comment by brtptrs** [comment]
In the app config the options:
"Show Terms of Service" for link shares"
"Show Terms of Service" for email shares"

**Comment by brtptrs** [comment]
Maybe even different wording for different types, but the option to force external users on email shares to accept the terms of service before accessing data would be a great start.

**Comment by nextcloud101** [comment]
This is exactly what we need!

**Comment by nextcloud101** [comment]
Hi,
is it possible to get a feedback on how likely an implemantation of this feature will be in a future version?
Thank you.

**Comment by nickvergessen** [comment]
At the moment it's very unlikely. But if you are a Nextcloud Customer with a Subscription, you can bring this up in your next mail/call with your account manager to back up the idea.

**Comment by dszego** [comment]
What is the point of terms of service for *registered* users? I gave them a password, I can already ensure (through other means) that they are beholden to certain terms of service.

If this app doesn't show TOS to *unregistered* users, it's really no use...

**Comment by nickvergessen** [comment]
Well you might hand out the password to all your users.
in other scenarios there is a registration app, signup page, group admins and other options to add users, so the admin can use this app to tell people the agreements of their service.

**Comment by daita** [comment]
Last version of ToS should do this.

However, there is no GUI settings. Meaning you will need to run the following occ command to enable the ToS on public shares:

>      ./occ config:app:set --value '1' terms_of_service tos_on_public_shares

**Comment by cesin10** [comment]
To display the Terms of Service for registered users and for public links type:

"Config value tos_on_public_shares for app terms_of_service set to 1"
command:
./occ config:app:set terms_of_service tos_on_public_shares --value '1'

Config value tos_for_users for app terms_of_service set to 1
command:
./occ config:app:set terms_of_service tos_for_users --value '1'
