### ISSUE TITLE
Exclude compressed js from Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/terms_of_service#18]
https://github.com/nextcloud/terms_of_service/blob/90416885287d8443f428e7dde9ce2d2fbf65e6e1/js/terms_of_service_user.js#L8

Please exclude strings from being shown at Transifex.
@MorrisJobke Here is another one like we had in the last weeks.

Another one for nextcloud/docker-ci#100

**Comment by rakekniven** [comment]
@nickvergessen Why closing it? Strings are still at Transifex (92 languages * 19) = 1748 strings which wasting time of translators.

**Comment by nickvergessen** [comment]
yeah, but it is nothing we can fix in this app. it needs to be fixed in the docker-ci
