### ISSUE TITLE
Calling ToS on certain page load

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/terms_of_service#192]
Is there a function I can call to have the ToS pop up when a certain page is loaded? I am currently working on modifying an app to my needs. I am unfortunately not a programmer, so I'd be very thankful for input.

Like if a certain app is opened - even when not logged in - I want this to show up.

Thanks in advance!

**Comment by nickvergessen** [comment]
That is not easily possible, because the check is done on the login of the user.
