### ISSUE TITLE
Modal dialog is unreadable on mobile devices

### ISSUE THREAD

**Issue by stackcoder** [nextcloud/terms_of_service#232]
When accessing nextcloud using mobile devices, especially when using a share link the modal dialog does not fit into screen so no one can read the cropped terms of service. This bug is related to some vue-js-modal issues ([#335](https://github.com/euvl/vue-js-modal/issues/335), [#346](https://github.com/euvl/vue-js-modal/issues/346)). They purport their component as _mobile-friendly_, in fact currently this is just a lie.

You can easily verify this by using their own official demo page: http://vue-js-modal.yev.io/

![Screenshot from 2019-08-28 23-50-40](https://user-images.githubusercontent.com/4529523/63895237-d259a300-c9ee-11e9-92e0-9fdb87259c59.png)

Because it looks for me that they are unable to get this fixed, I would suggest to switch to another component like sweet-modal-vue. What do you think?

**Comment by nickvergessen** [comment]
> Because it looks for me that they are unable to get this fixed, I would suggest to switch to another component like sweet-modal-vue. What do you think?

Feel free to shot in a PR

**Comment by euvl** [comment]
Hey there 👋 Have you tried setting property `:adaptive="true"`?

**Comment by nickvergessen** [comment]
Hi @euvl thanks for the hint, that does the trick it seems.
