### ISSUE TITLE
Overview who has acknoledged and location of storage

### ISSUE THREAD

**Issue by ArminP160** [nextcloud/terms_of_service#265]
Hi there, app works really fine - but we need to know who has signed and who is missing. An overview would be helpful - at least where in the database this is visible - Cheers - Armin

**Comment by nickvergessen** [comment]
In the database `oc_termsofservice_terms` keeps the terms (and which country/language they are displayed to)
and `oc_termsofservice_sigs` contains a map of the terms, user and the timestamp of signature

**Comment by ArminP160** [comment]
Cool! Thanks for super quick reply. Best - Armin
