### ISSUE TITLE
Horizontal Overflow on mobil

### ISSUE THREAD

**Issue by JUVOJustin** [nextcloud/terms_of_service#266]
I noticed there is a very unpretty horizontal overflow on mobie devices. As far as i was able to debug this behaviour this is caused by the javascript setting the absolute positioning. 

Removing the "left" attribute fixed the overflow.
Screenshot attached.
![Screenshot_2019-11-18 Dateien - JUVO Webdesign](https://user-images.githubusercontent.com/30726576/69054586-30a18b00-0a0c-11ea-9981-7cfe1575f3bf.png)

**Comment by nickvergessen** [comment]
This was already fixed with #243 

But I just noticed I never released this. I will put it on my todo for this week.
