### ISSUE TITLE
Where are the signatories located on the Server ? 

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/terms_of_service#296]
Steps to reproduce
Where are the signatories located on the Server ? Is this kind of acceptance (terms of service) a proofed way for a cloud provider in a case of an Audit (Security,Law...) ?

Expected behaviour
at least the ADMIN of the Cloud should see all Users, who already accepted the TOS.

Actual behaviour
ADMIN has got no control over the accepted TOS of the users.

Server configuration detail
Operating system: Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64

Webserver: Apache (apache2handler)

Database: mysql 5.5.64

PHP version:

7.2.24 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, imagick, redis, Zend OPcache

Nextcloud version: 16.0.7 - 16.0.7.1

Updated from an older Nextcloud/ownCloud or fresh install: updated from origin

Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: local/smb/sftp/...

Are you using encryption: no

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
no

Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

Enabled:

 - terms_of_service: 1.2.3

**Comment by nickvergessen** [comment]
They are stored in the database in the `oc_termsofservice_sigs`

Whether or not that is enough of a proof for your laws/security depends on what you refer to.

**Comment by Githopp192** [comment]
Thanks Joas. 
Maybe it would be helpful for the administrators if they could access those information on the web interface (maybe also for audit purposes)

**Comment by Githopp192** [comment]
btw ..  yesterday i did reset  --> Reset all signatories .. and i did change the ToS .. my expectation was then, than one user, who did already accept the ToS, that this user would get a new request for accept the ToS .. but after resetting all signatories .. user did not get a new request.

Should i log a new issue about, or did i misinterpret something ?

**Comment by nickvergessen** [comment]
Yes a new issue please, because that should happen.

**Comment by Githopp192** [comment]
just checked .. the one user now accepted the new ToS (checked the DB-Table) .. so it seems to work .. (maybe with some delay .. but this is ok)

**Comment by Githopp192** [comment]
i think - at the moment - no more issues there .. close it
