### ISSUE TITLE
No changes after installing terms_of_service 1.4 on Nextcloud 18.0.2

### ISSUE THREAD

**Issue by EGVuser** [nextcloud/terms_of_service#314]
No Checkbox to accept Terms of service ist requested during the Logon.
The system looks like the App is not installed.
 
Maybe is the app incopatible with Nextcloud 18.0.2?
Nextcloud server: 18.0.2 running on Apache
Terms of service: 1.4.0

**Comment by nickvergessen** [comment]
Did you configure any ToS in the admin settings?

**Comment by EGVuser** [comment]
Yes, I have configured any ToS in Admin settings.

**Comment by nickvergessen** [comment]
Please make sure you comfigured on for the country `--`

**Comment by EGVuser** [comment]
I have Configured the ToS for Germany like shown in the following screenshot
![Nextcloud_screenshot](https://user-images.githubusercontent.com/62250151/76837340-b1458c00-6832-11ea-8c5f-4cb3e1f1509f.png)

**Comment by nickvergessen** [comment]
Then you ip is not resolvable for Geo IP. Please add ToS for the country `--` or change your existing ToS to that country

**Comment by EGVuser** [comment]
The Nextcloud is running behind a reverse proxy.
The Cloud Server is using a private IP.
The IP of the reverse proxy points to Germany Like configured in ToS.

**Comment by nickvergessen** [comment]
If your reverse proxy is configured correctly the actual IP of the user is used for comparison. Please give `--` a test as mentioned above.
