### ISSUE TITLE
Error: Class 'MaxMind\Db\Reader' not found

### ISSUE THREAD

**Issue by marv0n** [nextcloud/terms_of_service#32]
When activating the plugin from the nextcloud appstore I get the following two errors:

> Error: Class 'MaxMind\Db\Reader' not found

> Error: Class 'MaxMind\Db\Reader' not found at /nextcloud/apps/terms_of_service/lib/CountryDetector.php#46

**Comment by nickvergessen** [comment]
I just published 1.0.1 in the appstore, which should fix this issue:
https://apps.nextcloud.com/apps/terms_of_service
