### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by ynjo** [nextcloud/terms_of_service#35]
Hi,
the version 1.0.1 solves the missing class issue, but now I get:
"Error  PHP   Uninitialized string offset: 0 at /var/www/nextcloud/lib/private/URLGenerator.php#227"

**Comment by bovender** [comment]
Confirmed. Log is full of this exact error message including line number.

**Comment by StadtBadWurzach** [comment]
Here the same: `Uninitialized string offset: 0 at /x/nextcloud/lib/private/URLGenerator.php#227`

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/terms_of_service/pull/72/files should solve the problem.
Feel free to change it on your instances until an update is released.
