### ISSUE TITLE
Trying to access array offset on value of type null at /var/www/html/custom_apps/terms_of_service/lib/CountryDetector.php#52

### ISSUE THREAD

**Issue by kylethedeveloper** [nextcloud/terms_of_service#367]
Hi,

I am using "Terms of Service" in my Nextcloud server and it works fine however this error is logged constantly and I could not figure out how to solve.

```
[PHP] Error: Trying to access array offset on value of type null at /var/www/html/custom_apps/terms_of_service/lib/CountryDetector.php#52

GET /apps/terms_of_service/terms
from 172.18.0.1 by admin at 2020-06-27T12:46:40+00:00
```
![Screenshot of logging page](https://i.imgur.com/nvu0PlQ.png "Screenshot of logging page")

I have a Docker installation of Nextcloud.
I can answer any questions if that might help to solve this issue.

Thanks.

**Comment by nickvergessen** [comment]
Seems like `vendor/GeoLite2-Country.mmdb` wasn't fully uploaded to your server?

**Comment by kylethedeveloper** [comment]
I don't know what that is, how do I do that?

**Comment by kylethedeveloper** [comment]
I checked the `vendor/GeoLite2-Country.mmdb` file. It was on my system. I re-downloaded it from [the repository](../blob/master/vendor/GeoLite2-Country.mmdb) into the _vendor_ folder but **it did not work.** I also checked and fixed the _owner_ information after I downloaded.

The logging continues rapidly.

**Comment by nickvergessen** [comment]
Sorry, it's the first time someone gets an error like this. Never saw it before.
It seems reading the database does not work on your maschine. Can you check your servers errorlog (not the nextcloud log) if there are further related issues logged?

**Comment by BRAVO68WEB** [comment]
I think you have no Terms submitted in the Terms of Service App. Giving a Global Signature or Terms will resolve the issue completely . Worked for me.

**Comment by BRAVO68WEB** [comment]
> 
> 
> I think you have no Terms submitted in the Terms of Service App. Giving a Global Signature or Terms will resolve the issue completely . Worked for me.

Try and Reply

**Comment by kylethedeveloper** [comment]
> I think you have no Terms submitted in the Terms of Service App. Giving a Global Signature or Terms will resolve the issue completely . Worked for me.

@BRAVO68WEB 
I didn't really understand what you mean. I have a _Global (Turkish)_ terms of service defined already. People can see and accept it with no problem. But I get the error.
Here is my Terms of Service page:
![tos-page](https://i.imgur.com/xi1NVBC.png)

**Comment by BRAVO68WEB** [comment]
@kylethedeveloper I was getting the same error but it resolved after I did that

Check mine
![IMG_20200721_111101](https://user-images.githubusercontent.com/41448663/88017301-0546e100-cb43-11ea-8247-6bd0e4d78fb0.jpg)

**Comment by nickvergessen** [comment]
Well the error message is not the same and the issue from this report is clearly that something is wrong with the country database

**Comment by Githopp192** [comment]
### Steps to reproduce
permanent flood error

same errors .. seems NC tries to get the country code from the ROUTERs (not on localhost) !?

### Expected behaviour
no errors

### Actual behaviour
log will be flooded with -->

[PHP] Error: Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52

GET /apps/terms_of_service/terms


## Server configuration detail

**Operating system:** Linux 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.17

**PHP version:** 

7.4.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, imagick, msgpack, smbclient, zip, memcached, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 19.0.2 - 19.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 18.0.8

**Where did you install Nextcloud from:** origin

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - analytics: 2.4.1
 - announcementcenter: 3.8.1
 - apporder: 0.11.0
 - audioplayer: 2.11.2
 - bookmarks: 3.3.4
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - circles: 0.19.5
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - cookbook: 0.7.6
 - cospend: 1.0.5
 - data_request: 1.6.0
 - dav: 1.15.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - drawio: 0.9.7
 - event_update_notification: 1.0.2
 - extract: 1.2.4
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_antivirus: 3.0.0
 - files_downloadactivity: 1.8.0
 - files_mindmap: 0.0.22
 - files_pdfviewer: 1.8.0
 - files_photospheres: 1.19.1
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - flowupload: 1.0.0
 - forms: 2.0.4
 - groupfolders: 7.0.0
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 5.0.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.4.3
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quicknotes: 0.6.0
 - quota_warning: 1.8.0
 - rainloop: 7.0.2
 - ransomware_protection: 1.7.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 9.0.3
 - support: 1.2.1
 - suspicious_login: 3.2.1
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - terms_of_service: 1.5.1
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.9.0
 - video_converter: 0.1.4
 - viewer: 1.3.0
 - workflow_script: 1.4.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - breezedark
 - carnet
 - dashboard
 - dicomviewer
 - drop_account
 - encryption
 - external
 - files_accesscontrol
 - files_external
 - files_fulltextsearch
 - files_markdown
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - impersonate
 - joplin
 - jsloader
 - ownbackup
 - passman
 - passwords
 - radio
 - ransomware_detection
 - richdocuments
 - sharerenamer
 - socialsharing_googleplus
 - survey_client
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       removed
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/removed",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "19.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "removed",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "removed",
    "session_lifetime": 1200,
    "session_keepalive": false,
    "logtimezone": "removed
    "logfile": "\/media\/log\/nextcloud.log",
    "knowledgebaseenabled": false,
    "log_rotate_size": removed,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44

**Operating system:** W10

## Logs

**Comment by Githopp192** [comment]
maybe i found the solution, which fixed it .. i did install "bind-utils" for Centos .. because i needed "nslookup" .. since then all the messages disappeared from log

**Comment by nickvergessen** [comment]
Can someone with a log entry like this post me the full line from the nextcloud.log file?

```
cat /var/www/html/data/nextcloud.log | grep 'Trying to access array offset on value of type null at' | grep 'terms_of_service'
```

**Comment by BRAVO68WEB** [comment]
Check if Global TOS is define by you or not

**Comment by Githopp192** [comment]
yes .. nickvergessen.. that's my output -->cannot fully understand for that moment .. why the remoteAddr is the router !? -->

{"reqId":"X3HyR-FJmy7xTqhtD2ykxQAAATc","level":3,"time":"2020-09-28T16:25:11+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyR-FJmy7xTqhtD2ykxQAAATc","level":3,"time":"2020-09-28T16:25:11+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyR-FJmy7xTqhtD2ykxQAAATc","level":3,"time":"2020-09-28T16:25:11+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyR-FJmy7xTqhtD2ykxQAAATc","level":3,"time":"2020-09-28T16:25:11+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyS-FJmy7xTqhtD2yk7gAAAZE","level":3,"time":"2020-09-28T16:25:15+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyS-FJmy7xTqhtD2yk7gAAAZE","level":3,"time":"2020-09-28T16:25:15+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyS-FJmy7xTqhtD2yk7gAAAZE","level":3,"time":"2020-09-28T16:25:15+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyS-FJmy7xTqhtD2yk7gAAAZE","level":3,"time":"2020-09-28T16:25:15+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyUfFJmy7xTqhtD2ylEgAAAds","level":3,"time":"2020-09-28T16:25:21+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyUfFJmy7xTqhtD2ylEgAAAds","level":3,"time":"2020-09-28T16:25:21+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyUfFJmy7xTqhtD2ylEgAAAds","level":3,"time":"2020-09-28T16:25:21+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HyUfFJmy7xTqhtD2ylEgAAAds","level":3,"time":"2020-09-28T16:25:21+02:00","remoteAddr":"192.168.2.1","user":"Michael","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HybI18VGKD-uhHIB7BgwAAAPc","level":3,"time":"2020-09-28T16:25:48+02:00","remoteAddr":"192.168.2.1","user":"admin","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HybI18VGKD-uhHIB7BgwAAAPc","level":3,"time":"2020-09-28T16:25:48+02:00","remoteAddr":"192.168.2.1","user":"admin","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HybI18VGKD-uhHIB7BgwAAAPc","level":3,"time":"2020-09-28T16:25:48+02:00","remoteAddr":"192.168.2.1","user":"admin","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
{"reqId":"X3HybI18VGKD-uhHIB7BgwAAAPc","level":3,"time":"2020-09-28T16:25:48+02:00","remoteAddr":"192.168.2.1","user":"admin","app":"PHP","method":"GET","url":"/apps/terms_of_service/terms","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51","version":"19.0.3.1"}
"/tmp/list" 36L, 17952C

**Comment by nickvergessen** [comment]
`"remoteAddr":"192.168.2.1"`

Okay, seems like you are using a wrongly configured proxy/reverse-proxy on top of Nextcloud. Let me check if we can prevent the error and instead log something more useful.

**Comment by Githopp192** [comment]
Hm .. nickvergessen..  kylethedeveloper also got the error with remote address on the gateway (172.18.0.1), like me (192.168.2.1) .. and i have no proxy server installed on top of nextcloud

**Comment by nickvergessen** [comment]
yeah it will bne fixed in the next version

**Comment by Githopp192** [comment]
upgraded to 19.0.4; result -->

Error: Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php#52
/var/www/html/nextcloud/apps/terms_of_service/lib/CountryDetector.php - line 52:

OC\Log\ErrorHandler::onError()

/var/www/html/nextcloud/apps/terms_of_service/lib/Checker.php - line 87:

OCA\TermsOfService\CountryDetector->getCountry()

/var/www/html/nextcloud/apps/terms_of_service/lib/Controller/TermsController.php - line 95:

OCA\TermsOfService\Checker->currentUserHasSigned()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

OCA\TermsOfService\Controller\TermsController->index()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 137:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main()

<<closure>>

OC\AppFramework\Routing\RouteActionHandler->__invoke()

/var/www/html/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func()

/var/www/html/nextcloud/lib/base.php - line 1011:

OC\Route\Router->match()

/var/www/html/nextcloud/index.php - line 37:

OC::handleRequest()
