### ISSUE TITLE
ToS only for Public Link Shares

### ISSUE THREAD

**Issue by sleeplessnight2** [nextcloud/terms_of_service#391]
It is currently the case that ToS also affects the entire Webdav - i.e. external apps that use the Webdav via the app passwords that can be created.

So it is no longer possible with ToS, e.g. to move between Android and the Webdav files.

One solution would be that you can select in the admin panel whether you want to allow file access without confirmation or not.

**Comment by nickvergessen** [comment]
If you do not agree to the terms of service you can not use the service.

I don't think adding an option to still allow using the service while you do not agree to the terms is something we should allow (even optional).

**Comment by sleeplessnight2** [comment]
That makes sense. But how is a simple app supposed to confirm such a query? Smartphone apps like FolderSync, backup apps etc.? I'm glad if I find anything like input fields username and password ...

Especially for such apps, NC developed an "app password" that can be used instead of the normal user password to e.g. bypass the 2-factor authentication.

If i used the ToS, my Server Logs Show's this, if i try to sync any Folder with such apps:
If I currently try to synchronize folders of such apps, I get the following error messages:

```
[webdav] Fatal: OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions at <<closure>>

 0. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 195
    OCA\DAV\Connector\Sabre\Directory->getChildren()
```

**Comment by nickvergessen** [comment]
Well show an error to the user on `No read permissions` to check the UI?

**Comment by sleeplessnight2** [comment]
No, this error shows at the server logs. The Apps itselfs create own error messages. In case of FolderSync "Permission Denied".

I think ToS ignores the `tos_for_users --value '0'` flag for such smartphone apps.
Since the apps log in using their username and app password, they belong in the "register user" area and are no longer public ...
