### ISSUE TITLE
Typographical errors

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/terms_of_service#42]
Taiwan is not province of China.
Please check Wikipedia.
And fix this Typographical.

https://en.m.wikipedia.org/wiki/Taiwan

https://en.m.wikipedia.org/wiki/China

Thanks.

**Comment by nickvergessen** [comment]
Sorry, didnt mean to hurt any feelings, I just read https://en.wikipedia.org/wiki/Taiwan and see it is complicated.

**Comment by chiyi4488** [comment]
Maybe a few years later Taiwan will become a province in China, but at least not now. I hope to fix it in the next release. Because the person using this name is a Taiwanese, the terms of certain manufacturers and merchants may conflict. After all, the current Taiwanese government is not under the control of China.
