### ISSUE TITLE
Can't display terms of service for user.

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/terms_of_service#48]
I used nextcloudpi(raspberry).
I can't display my terms of service for my user.
I don't know why.so if need any data. please let me know.

Thanks.

**Comment by nickvergessen** [comment]
did you set any ToS for the country "global"?
Otherwise make sure the detected country has ToS assigned, because otherwise there will be none displayed.

**Comment by chiyi4488** [comment]
I set up "Taiwan Province of china".

**Comment by chiyi4488** [comment]
Oh.I see.if I set up "global",it can display.
But I set up"Taiwan of province china.
It can't display.
