### ISSUE TITLE
Nextcloud 21

### ISSUE THREAD

**Issue by sunjam** [nextcloud/terms_of_service#480]
Please add support.  Thanks for the great app!

**Comment by nickvergessen** [comment]
Hi @sunjam thanks for the reminder. I knoe 21 was released anf i will publish updates for all my apps soon, no need to create an issue everywhere. Thanks

**Comment by sunjam** [comment]
Hopefully the process will be automated someday, because people do actually
rely on these apps. I know you personally are connected to nc, but most
devs are not. And these things fall through the cracks sometimes. So feel
free to close it or disregard. No doubt my own limited time will hinder me
from reporting on possible update conflicts in the future.  It is
frustrating to see so many NextcloudPi admins wanting to update to the
latest, then getting frustrated by incompatibilities, so we can generally
discourage from updating stables too quickly (we are currently pushing
20.0.4). Hope that makes sense. :)

**Comment by nickvergessen** [comment]
Will delay the release of this one until  #471 is solved. Something seems to have changed/broken that config.

**Comment by nickvergessen** [comment]
1.7.0 is in the appstore
