### ISSUE TITLE
L10n bot found a wrong translation in this JS line

### ISSUE THREAD

**Issue by castillo92** [nextcloud/terms_of_service#527]
https://github.com/nextcloud/terms_of_service/blob/0d1bbe876a07ad8b31702c3f576ce85ab97e75b6/js/terms_of_service_registration.js#L7

I saw in Transifex the need of translating this words and all of them was from `Line 7` of `terms_of_service_registration.js`

```
keys
entries
min-height
min-width
auto
dialog
```

This could be a risk of broke JS because of a change of this words?

**Comment by castillo92** [comment]
This will be the fix:

https://github.com/nextcloud/terms_of_service/commit/31688db6538c2260304f43d1f39d77986829c523

**Comment by nickvergessen** [comment]
I forgot to backport it to 21
https://github.com/nextcloud/terms_of_service/pull/518

Done now, thanks for the hint.
