### ISSUE TITLE
Outdated @nextcloud/webpack-vue-config

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/terms_of_service#533]
Please upgrade @nextcloud/webpack-vue-config to our latests config
Also consider the following configs:

- @nextcloud/babel-config

cc @nickvergessen

**Comment by nickvergessen** [comment]
Hmm why didn't dependabot ping this yet?🤔

**Comment by skjnldsv** [comment]
Because this is a breaking major with lots of dependencies, you cannot have this automatically updated between majors, only minors and patches.
It shuld be fixed with npm7 tho
