### ISSUE TITLE
Translation incomplete

### ISSUE THREAD

**Issue by herbetom** [nextcloud/terms_of_service#54]
The Translation of "terms_of_service" seems to be a little incomplete.

In the window in which the user has to confirm the Terms the following not translated text is shown: 
"_I acknowledge that I have read and agree to the above terms of service_" . 

This should definitely be fixed.

Also in the Settings of the App some thinks are not translated, I will list them, but it is not that important.
"_Require users to accept the terms of service before accessing the service._"
"_Select a region_"
"_Select a language_"
"_By using this service ..._"

**Comment by nickvergessen** [comment]
This is due to https://github.com/nextcloud/server/issues/11303

I added all strings manually in a plain JS file for now.
