### ISSUE TITLE
No error Message when no region or language is selected

### ISSUE THREAD

**Issue by herbetom** [nextcloud/terms_of_service#55]
It would be nice if there would be an Error Message if you forgot to select a region or language from the list in the Admin Interface. 

Currently if you want to add only one text for all you have to wonder why the Terms are not saved and I first thought the settings are broken until i figured out that you have to specify the region and language.

**Comment by gary-kim** [comment]
I can work on this.

**Comment by herbetom** [comment]
Thanks!
