### ISSUE TITLE
Terms and Conditions on main page and registration page

### ISSUE THREAD

**Issue by arteteco** [nextcloud/terms_of_service#574]
Hello all,
I'd like inform my potential users that there are some guidelines on using the platform, and the process to get an account (after registration they must be manually verified, anyway that's just a personal thing).

So, I'm really missing on a page when a user is signing up, or simply in the home page, with the Term and Condition, possibly with the possibility of using any name. As of now, there is only Legal Notice and Privacy Policy as customizable links in the home page.

Thanks!

**Comment by nickvergessen** [comment]
This works with the latest versions of registration and terms of service app already
