### ISSUE TITLE
Terms of Service shows nealy empty field during registration process

### ISSUE THREAD

**Issue by EGVuser** [nextcloud/terms_of_service#620]
ToS shows the foolowing field during the User registration process 

![grafik](https://user-images.githubusercontent.com/62250151/132349216-c38c0b2c-ba14-494b-91e3-e31e3bc44982.png)

But if User needs to accept Tos during the Login Process ToS look like expected.

<details><summary>Configuration (config/config.php)</summary>

{
    "updatechecker": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.224.32.25",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/10.224.32.25",
    "dbtype": "mysql",
    "version": "21.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de_DE",
    "default_phone_region": "DE",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "loglevel": 0,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "maintenance": false,
    "allow_user_to_change_display_name": false,
    "session_lifetime": 900,
    "trashbin_retention_obligation": "auto, 14",
    "log_rotate_size": 104857600,
    "log_rotate_sizerotation": 524288000,
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR",
        "HTTP_X_FORWARDED"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "htaccess.RewriteBase": "\/",
    "memcache.locking": "\\OC\\Memcache\\APCu",
    "theme": "",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "Testgruppe",
        "Test2"
    ],
    "twofactor_enforced_excluded_groups": [
        "LVH_Hardehausen",
        "Testgruppe",
        "ZA-Entwicklung",
        "ZA-IT-Betrieb",
        "ZA-IT-Projekte",
        "ZA-IT-Referenten",
        "ZA_IT"
    ],
    "updater.release.channel": "stable",
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"

<details><summary>List of activated apps</summary>
}Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - bbb: 2.0.0
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.3
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.2
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - data_request: 1.8.0
 - dav: 1.17.1
 - documentserver_community: 0.1.11
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.3.0
 - groupfolders: 9.0.3
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.1.2
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - registration: 1.3.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.3.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - terms_of_service: 1.7.1
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_ldap: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - encryption
 - federation
 - files_external
 - twofactor_totp

**Comment by nickvergessen** [comment]
Can you share the theming color value? And since you talk about registration, is the OS dark or bright themed? (If you don't know share a folder publicly  and open the link in a logged out window)

**Comment by EGVuser** [comment]
![grafik](https://user-images.githubusercontent.com/62250151/132452031-9b12a34a-3e5e-4030-a533-771be67f4d91.png)

The System is bright themed, i think.
![grafik](https://user-images.githubusercontent.com/62250151/132452228-757c9b32-cd7a-4fbf-9739-6b49d2cbd3e1.png)
![grafik](https://user-images.githubusercontent.com/62250151/132452658-91407081-5d91-4df4-917b-a572dc69a133.png)

**Comment by EGVuser** [comment]
Is there already a version of ToS available that contains the bugfix Fix CSS selector after upgrade of vue-js-modal # 621?
Or when do you expect a corresponding package? 
Unfortunately I am not a software developer.

**Comment by nickvergessen** [comment]
I will do a new version for the appstore soon.

**Comment by nickvergessen** [comment]
1.8.1 is available now

**Comment by EGVuser** [comment]
Unfortunately, version 1.8.1 did not solve the problem on my system.
I was only able to test ToS 1.8.1 now because I first had to manually update to NextCloud version 22.1.1.

As a workaround, by uploading a login image in the Theming App, I was able to ensure that my Terms of Service are also displayed correctly during registration.
