### ISSUE TITLE
TOS and Reverse Proxy

### ISSUE THREAD

**Issue by AndrinS** [nextcloud/terms_of_service#678]
We're experiencing a problem that the TOS only show up once. Not once per share or source but once for everyone.

We use Nextcloud in combination with a reverse proxy (HAproxy). Is it possible that the TOS app registers the IP from the proxy and not the actual source IP and thus only showing the TOS one time?

**Comment by nickvergessen** [comment]
Please check the settings: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by nickvergessen** [comment]
Closing as I assume that solved it.
