### ISSUE TITLE
Registration integration: Android Browsers using dark theme present headline and links in a greyish color

### ISSUE THREAD

**Issue by scmarti** [nextcloud/terms_of_service#685]
On Android, Browsers Chromium 85.0.4151.0 and Firefox 97.1.0 set to use a dark theme (either explicitly or via the systems theme being dark) present the headline and any link in the body of the ToS confirmation dialogue integrated into the registration in a greyish color (maybe translucent?) instead of solid black.

![IMG_20220214_215321](https://user-images.githubusercontent.com/16196999/153944984-43837b39-f985-4a5a-b4a6-22602f6001b2.jpg)

Text will be presented white on white (s. #620)

**Comment by nickvergessen** [comment]
Please make sure you run the latest version of the apps and server

**Comment by scmarti** [comment]
Thank you for your quick reply! I am running the latest nextcloud version the stable release channel offers, Nextcloud Hub II (23.0.0), and Terms of Service App Version 1.9.2 being the latest available for aforementioned nextcloud version.

**Comment by scmarti** [comment]
I just updated to Nextcloud 23.0.2. The described behaviour persists.

**Comment by nickvergessen** [comment]
Can not reproduce with FF 97.2 on Android with:
Nextcloud 23.0.2
Registration: 1.4.0
Terms of service 1.9.2

**Comment by scmarti** [comment]
Thanks for your effort!
I just reproduced the descirbed behaviour with FF 97.2 on Android 10 (build: lineage_crackling-userdebug 10 QQ3A.200805.001 10039313) with 
Nextcloud 23.0.2
Registration 1.4.0
Terms of Service 1.9.2
Nextcloud > Settings > Design > Color: #222A8C

Did you activate a dark theme in the browsers settings? The behaviour does not occur when using a light theme.
Which steps did you take to reproduce?

**Comment by nickvergessen** [comment]
My dev side | Your site
---|---
![Screenshot_2022-02-23-09-39-23-837_org mozilla firefox](https://user-images.githubusercontent.com/213943/155285776-c12eac0a-09d0-49a6-bfae-5800cc6b5780.jpg) | ![Screenshot_2022-02-23-09-37-35-651_org mozilla firefox](https://user-images.githubusercontent.com/213943/155285784-2c8a9c88-84f7-4ba9-9aec-df445b1c2fe6.jpg)

**Comment by nickvergessen** [comment]
Closing as I think this should not be a problem anymore especially with the new UI in 25.
