### ISSUE TITLE
Layout of multiselect boxes is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/terms_of_service#76]
@skjnldsv you made a PR somewhere regarding multiselect, I think 2 thigns are incompatible? can you have a look here?

> ![bildschirmfoto von 2018-11-22 15-59-53](https://user-images.githubusercontent.com/213943/48910240-b88f9c00-ee6f-11e8-80a8-fe32947f70fe.png)

**Comment by skjnldsv** [comment]
Hey :grinning: 
It looks like you're using v-select.
Please switch to nextcloud's components Multiselect. It should we straightforward.

I removed a multiselect but it was not linked to this one :)

**Comment by nickvergessen** [comment]
Thanks works great, only the placeholder is padding 0, instead of having a little padding to the left border.

**Comment by skjnldsv** [comment]
> Thanks works great, only the placeholder is padding 0, instead of having a little padding to the left border.

Yes, this is fixed in https://github.com/nextcloud/nextcloud-vue/pull/118
Will be released soon :)
