### ISSUE TITLE
Swedish translation files missing from Transifex

### ISSUE THREAD

**Issue by maghog** [nextcloud/terms_of_service#84]
Swedish (sv) translation files from Transifex is not included.

**Comment by nickvergessen** [comment]
Yeah, seems like it was only translated yesterday. It is now synced into the repository (happens every morning between 7and8).

If you need the translations, you can copy the `sv.*` files from https://github.com/nextcloud/terms_of_service/tree/master/l10n yourself, or you will have to wait until the next release is build.

Does that solve your question?

**Comment by maghog** [comment]
Yes, thanks!
