### ISSUE TITLE
Benutzerauflistung für Akzeptierte Nutzungsbedingung im Admin-Bereich

### ISSUE THREAD

**Issue by MarcK594** [nextcloud/terms_of_service#886]
Gibt es eine Möglichkeit im Administratorbereich zusehen, wer die Nutzungsbedingung akzeptiert hat?

Hier wäre eine zusätzliche Spalte in der Benutzerliste hilfreich.

**Comment by max-nextcloud** [comment]
Hi @MarcK594 

As far as i know this is not possible yet. The feature has already been requested here: #703 

If you are an enterprise customer please get in contact with Nextcloud support or your account manager to request this feature so it can be prioritized.

Closing this issue as duplicate.
