### ISSUE TITLE
Mobile and desktop client do ignore the confirmation

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/terms_of_service#98]
The GDPR will make regular changes of the terms of use necessary in the near future, since many of it's regulations concretize themselves only through jurisdiction.
The App can indeed request new confirmation with each change, but only browser based. Users that are using the Cloud over the Nextcloud Desktop client or the mobile Apps will never see the changes.
This can cause legal problems for cloud operators.
Is there a chance to force a browser-login the way it is done when authenticating the client or app?

**Comment by nickvergessen** [comment]
Well they can not use files until they accepted the new terms. Also both clients receive a notification that there are terms which need accepting.

Or did I misunderstood your point?

**Comment by Volker-K** [comment]
The iOS App says that you're not allowed to access the specific file as long as it isn't already cached on the device. That's right, seems I've only tested cached files yesterday.
Could the message possibly be more telling? Sort of "Please login with your browser, there's a need for action"?

**Comment by nickvergessen** [comment]
> Update: Just checked Desktop Client for Windows, 2.5.0 on Windows 10. In case there are new Terms of Service pending to be accepted it only reports a "403 Forbidden" from the server.

But it should show the notification to accept the terms in the meantime.
