### ISSUE TITLE
Allow to send (push) notification if new ToS needs to be signed

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/terms_of_service#991]
Currently if there is an update to ToS no info is shown to the user.
The user just experiences that it is not working, if they are in web.

Instead we should send optional (push) notifications, so that users are informed.

**Comment by nickvergessen** [comment]
There are notifications. They are sent initially or after the "Reset all signatures" button was pressed:
![Image](https://github.com/user-attachments/assets/5bcee5b9-2819-4b71-a252-6274dfcd136d)

**Comment by tobiasKaminsky** [comment]
Indeed. My test was wrong.
